### ISSUE TITLE
Weather widget misaligned

### ISSUE THREAD

**Issue by esazsX** [evancohen/smart-mirror#369]
The weather widget is no longer touching the border of the frame, and has been moved closer to the center

**Comment by glcohen** [comment]
I changed main.css:191 to "margin-left: 75px;" which fixed the misalignment for me.

**Comment by evancohen** [comment]
@glcohen I think that just adds additional padding to the `.weather` class. I think what really has to happen is that it needs to be of `display: block;` which will fix the left margin issue.

``` css
.weather {
    margin-left: auto;
    display: block;
    text-align: right;
    width: 228px;
}
```
